# Generated by Django 5.2.6 on 2025-09-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusartistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='imagem',
        ),
    ]
