# Generated by Django 5.2.6 on 2025-09-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusartistas', '0002_remove_artista_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
