# Generated by Django 5.2.6 on 2025-09-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusartistas', '0003_artista_imagem_artista_mbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='mbid',
            new_name='itunes_id',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='nascimento',
        ),
    ]
