# Generated by Django 5.2.6 on 2025-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusartistas', '0004_rename_mbid_artista_itunes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='album_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='track_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
