# Generated by Django 5.2.6 on 2025-09-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('capa_url', models.URLField(blank=True, null=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
