# Generated by Django 5.2.6 on 2025-09-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='capa_url',
        ),
    ]
