# Generated by Django 5.2.6 on 2025-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_remove_musica_api_id_remove_musica_capa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
