# Generated by Django 5.2.6 on 2025-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_alter_musica_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='capa_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
